sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- pip install --user codecov
after_success:
- codecov
