/*
 * The MIT License
 *
 * Copyright (c) 2025 Fulcrum Genomics LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.fulcrumgenomics.umi

import com.fulcrumgenomics.FgBioDef._
import com.fulcrumgenomics.bam.api.SamRecord
import com.fulcrumgenomics.testing.SamBuilder.{Minus, Plus}
import com.fulcrumgenomics.testing.{SamBuilder, UnitSpec}
import com.fulcrumgenomics.util.Sequences
import org.scalatest.OptionValues

import scala.util.Random

class CodecConsensusCallerTest extends UnitSpec with OptionValues {
  // Sequence to make reads from; each line is exactly 100 bases long
  private val RefBases = Seq(
    "TGGGTGTTGTTTGGGTTCCTGCTTAAAGAGCTACTGTTCTTCACAGAAACTTCCAACTCACCCAGACTGAGATTTGTACTGAGACTACGATCCACATGTT",
    "CAATATCTGATATCTGATGGGAAATAGGCTTTACTGAATTATCCATTTGGGCTGTAATTAATTTCAGTGATGAGCGGGAGATGTTGTTAGTTGTGCTCAG",
    "TAACTTTTTGATAGTAGCGGGAGTAGGAGTAAATCTTGTACTAATTAGTGAATATTCTGTTGATGGTGGCTGAAAATTTATAGCTACACAACCAAAAAAT",
    "AAAAAACGTTAGTCAATAGCATTTATAAATAGTCTTCTCTACCTGAAATATTTTACATTAAGTAATTCATTCCTTCATTTAGTATCTACACATGTCTAAC",
    "ATTGTAGTAGGAGCTGTGTACTAACAAGAAATCATGACACTGTTTCTGCCTTCAAGGAGCTTATAATCTTTTGGGGTACACAAGATAACCCAGAATGTTA",
    "AATAGTATAAAAGTCAAAGTACAATAATTTATTTCATTAAGATTTTGAAATGGCTAACAAACACCTGTTGATCACCTCATACACATGAGCCTCAAAACAA",
    "AGGAAAGCACAGCCCCTATGCCTGAGCAATTTAGAATATTGTCAAGGATAGAGACATGTGAGCCATTCACTATGAAACAATCATTGAGAACTACTACAAG",
    "AGTGATAAATATAAAATGAAACCTACAGAAACACAGAAGAGTAAGTAATTTTCCCTATAAAGAAGACAGGAACTAAATGTATAAGCAAAAATTGGGAAAT",
    "TATATAAATGCTATTTTATATGAGAGGCAAAGAACCACAGGTCTAATAATTTTACAAATGTGATAAAATCAGATTTTATGTCCCCATCTTTCTTGACTGC",
    "TCAGCTAGAAATTAAAACATTTTTACACATCTTTTTGGCGGGGGCGGGGGGGATCATTATTTATTTCACCTGCCAAAATACTTCATTTCCTTATTGCACT",
    "TTTTTACTTCTTTGGTATGGAAAAATCTAACGGGTTTTAGAGTATGAACACATTTTAAGCAGTGATTAGATACGTTTTTCTTGTTATGCTTTCTATTGCA",
    "AATTTAGGATTTGATTTTGCACTGTCTTCATGCAAAGCTCTTCTCAAAGGTCTTAAAATATAAAAAACACTTAATGCTTCTCAAAGCATTAAGATTTTAT",
    "GTAAATCAAACCAAAACCAGAAAAAGACAGAAGAAAATGAACCAAAAACAACAAAAATAATCCTTAACATAGTTGGCAACAAGTGCAATGAAAGATTTTT",
  ).mkString

  private val random = new Random()

  /** Adds a random sequence of the requested length to the provided StringBuilder.  */
  private def addRandomSequence(sb: StringBuilder, length: Int): Unit = {
    forloop (from=0, until=length) { _ =>
      val base = RefBases(random.nextInt(RefBases.length))
      sb.append(base)
    }
  }

  /** Takes a SamRecord generated by a SamBuilder and sets a valid read sequence on it from RefBases
    * based on the position on the record.
    */
  private def setReadSequence(rec: SamRecord): Unit = {
    val sb = new StringBuilder()
    var offset = rec.start - 1
    rec.cigar.iterator.foreach { elem =>
      if (elem.operator.consumesReadBases()) {
        if (elem.operator.consumesReferenceBases()) {
          sb.append(RefBases.substring(offset, offset + elem.length))
        }
        else {
          addRandomSequence(sb, elem.length)
        }
      }

      if (elem.operator.consumesReferenceBases()) {
        offset += elem.length
      }
    }

    rec.bases = sb.toString()
  }


  "CodecConsensusCaller.consensusSamRecordsFromSamRecords" should "make a consensus from two simple reads" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(contig=0, start1=1, start2=11, attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))).tapEach(setReadSequence)
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons should have length 1
    cons.head.name shouldBe "codec:hi"
    cons.head.length shouldBe 40
    cons.head.basesString shouldBe RefBases.substring(0, 40)
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }

  it should "make a consensus where R1 has a deletion outside of the overlap region" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(
      contig=0, start1=1, start2=13, cigar1="5M2D25M", cigar2="30M", attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))
    ).tapEach(setReadSequence)
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons.head.length shouldBe 40
    cons.head.basesString shouldBe (RefBases.substring(0, 5) + RefBases.substring(7, 42))
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }

  it should "make a consensus where R2 has a deletion outside of the overlap region" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(
      contig=0, start1=1, start2=11, cigar1="30M", cigar2="25M5D5M", attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))
    ).tapEach(setReadSequence)
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons.head.length shouldBe 40
    cons.head.basesString shouldBe (RefBases.substring(0, 35) + RefBases.substring(40, 45))
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }

  it should "make a consensus where the reads have soft-clipping outside of the overlap region" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(
      contig=0, start1=1, start2=11, cigar1="5S25M", cigar2="25M5S", attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))
    ).tapEach(setReadSequence)
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons.head.length shouldBe 45
    cons.head.basesString shouldBe raw.head.basesString.substring(0, 5) + RefBases.substring(0, 35) + raw.last.basesString.substring(25, 30)
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }

  it should "make a consensus where both reads are soft-clipped at the same end and fully overlapped" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(
      contig=0, start1=1, start2=1, cigar1="5S25M", cigar2="5S25M", attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))
    ).tapEach(setReadSequence)
    raw.last.bases = raw.head.basesString // Make sure they have the same soft-clipped sequence
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons.head.length shouldBe 30
    cons.head.basesString shouldBe raw.head.basesString.substring(0, 5) + RefBases.substring(0, 25)
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }

  it should "emit the consensus in the orientation of R1" in {
    val builder = new SamBuilder(readLength=30, baseQuality=35)
    val caller  = new CodecConsensusCaller(readNamePrefix="codec", minReadsPerStrand=1, minDuplexLength=1)
    val raw     = builder.addPair(
      contig=0, start1=11, start2=1, strand1=Minus, strand2=Plus, attrs=Map(("RX", "ACC-TGA"), ("MI", "hi"))
    ).tapEach(setReadSequence)
    val cons    = caller.consensusReadsFromSamRecords(raw)

    cons should have length 1
    cons.head.name shouldBe "codec:hi"
    cons.head.length shouldBe 40
    cons.head.basesString shouldBe Sequences.revcomp(RefBases.substring(0, 40))
    cons.head[String](ConsensusTags.UmiBases) shouldBe "ACC-TGA"
  }
}
